#!/usr/bin/env python3
"""Render derived IOR application and POSIX throughput points on a linear scale."""

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def parse_arguments():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--points",
        type=Path,
        default=DATA / "ior_io_layer_points.csv",
        help="I/O layer point CSV generated by analyze_ior_trace.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "ior_stack_linear.png",
        help="Output PNG path.",
    )
    return parser.parse_args()


def main():
    args = parse_arguments()
    with args.points.open(newline="", encoding="utf-8") as stream:
        points = list(csv.DictReader(stream))
    if not points:
        raise SystemExit(f"no I/O layer points in {args.points}")

    labels = [point["layer"].replace("_", " ") for point in points]
    bandwidths = [float(point["effective_bandwidth_gbs"]) for point in points]
    durations = [float(point["duration_seconds"]) for point in points]
    colors = ["#6f2dbd", "#9b2226"]

    figure, axis = plt.subplots(figsize=(8.5, 4.8), constrained_layout=True)
    positions = list(range(len(points)))
    bars = axis.barh(positions, bandwidths, color=colors[: len(points)], height=0.56)
    axis.set_yticks(positions, labels=labels)
    axis.invert_yaxis()
    axis.set_xlabel("Effective I/O throughput [GB/s]")
    axis.set_title("IOR Application and POSIX Stack Points (Linear Scale)")
    axis.set_xlim(0.0, max(bandwidths) * 1.25)
    axis.grid(True, axis="x", color="#d6d6d6", linewidth=0.7)

    for bar, bandwidth, duration in zip(bars, bandwidths, durations):
        axis.text(
            bar.get_width() + max(bandwidths) * 0.02,
            bar.get_y() + bar.get_height() / 2,
            f"{bandwidth:.4f} GB/s\n{duration:.6f} s",
            va="center",
            fontsize=10,
        )

    figure.savefig(args.output, dpi=180)
    print(f"plot={args.output}")


if __name__ == "__main__":
    main()